### ISSUE TITLE
Internal Service Error - (fc): Expired Transaction: expired transaction

### ISSUE THREAD

**Issue by satonz** [fioprotocol/fio-go#21]
How should I set the expiration time of the trade

**Comment by blockpane** [comment]
Hi @satonz, great question, and I think the default timeout of 30 seconds is too aggressive, so I'll bump up the default to 3 minutes which will make it into the next release. 

In the meantime I've added an example showing how to override the default here: https://github.com/fioprotocol/fio-go/blob/63af153fd12ec408fc4735dce3473289244a0061/_example/transfer-long-timeout.go
