### ISSUE TITLE
Trading training in rotation

### ISSUE THREAD

**Issue by satonz** [fioprotocol/fio-go#24]
I want the rotation training block, and all the trades in the rotation training block, but the trades I found so far cannot be read directly. Could you please provide a relevant Demo               thanks

**Comment by satonz** [comment]
Very anxious, please reply after you see, thank you very much

**Comment by blockpane** [comment]
Hello @satonz,

I've been out a few days, sorry for the delayed response. Can you help me understand what you are trying to accomplish? Are you trying to index all transactions in a block?

**Comment by satonz** [comment]
I want to retrieve all transactions in a block

**Comment by blockpane** [comment]
I've added a couple of examples in the develop branch: https://github.com/fioprotocol/fio-go/tree/develop/_example/_blocks
